import { AiFillStar } from "react-icons/ai";

const data = [
  {
    img: "https://hldak.mmtcdn.com/prod-s3-hld-hpcmsadmin/holidays/images/cities/260/Brussels.jpg?crop=259:168&downsize=259:168",
    title: "Stonehenge,Windsor Castle and Bath with",
    title1:"pub lunch in Lackok",
    title2:"London with guided Cathedal tour",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    newPrice: "200",
    location: "london",
    category: "tours",
    cancellation:'free cancellation',
    duration:'16'
  },
  {
    img: "https://hldak.mmtcdn.com/prod-s3-hld-hpcmsadmin/holidays/images/cities/235/vienna1.jpg?crop=259:168&downsize=259:168",
    title: "Westmister Walking tour & Westmister with ",
    title1:" Abbey entry London",
    title2:"guided Cathedal tour",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    newPrice: "200",
    location: "London",
    category: "tours",
    cancellation:'free cancellation',
    duration:'14'
  },

  {
    img: "https://hldak.mmtcdn.com/prod-s3-hld-hpcmsadmin/holidays/images/cities/18/Makhuntseti%20Waterfall.jpeg?crop=259:168&downsize=259:168",
    title: "Westmister Walking tour & Westmister with ",
    title1:" Abbey entry London",
    title2:"guided Cathedal tour",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    newPrice: "200",
    location: "London",
    category: "tours",
    cancellation:'free cancellation',
    duration:'14'
  },
  {
    img: "https://hldak.mmtcdn.com/prod-s3-hld-hpcmsadmin/holidays/images/cities/2145/Canal-in-Amsterdam.jpg?crop=259:168&downsize=259:168",
    title: "Westmister Walking tour & Westmister with ",
    title1:" Abbey entry London",
    title2:"guided Cathedal tour",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    newPrice: "10",
    location: "London",
    category: "tours",
    cancellation:'none',
    duration:'14'
  },
  {
    img: "https://hldak.mmtcdn.com/prod-s3-hld-hpcmsadmin/holidays/images/cities/235/vienna1.jpg?crop=259:168&downsize=259:168",
    title: "Westmister Walking tour & Westmister with ",
    title1:" Abbey entry London",
    title2:"guided Cathedal tour",    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    newPrice: "15",
    location: "Barcelona",
    category: "attractions",
    cancellation:'free cancellation',
    duration:'7'
  },
  {
    img: "https://hldak.mmtcdn.com/prod-s3-hld-hpcmsadmin/holidays/images/cities/235/vienna1.jpg?crop=259:168&downsize=259:168",
    title: "Westmister Walking tour & Westmister with ",
    title1:" Abbey entry London",
    title2:"guided Cathedal tour",    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    newPrice: "65",
    location: "Barcelona",
    category: "attractions",
    cancellation:'free cancellation',
    duration:'6'
  },

  {
    img: "https://hldak.mmtcdn.com/prod-s3-hld-hpcmsadmin/holidays/images/cities/235/vienna1.jpg?crop=259:168&downsize=259:168",
    title: "Westmister Walking tour & Westmister with ",
    title1:" Abbey entry London",
    title2:"guided Cathedal tour",    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    newPrice: "65",
    location: "Barcelona",
    category: "attractions",
    cancellation:'free cancellation',
    duration:'2'
  },

  {
    img: "https://hldak.mmtcdn.com/prod-s3-hld-hpcmsadmin/holidays/images/cities/235/vienna1.jpg?crop=259:168&downsize=259:168",
    title: "Westmister Walking tour & Westmister with ",
    title1:" Abbey entry London",
    title2:"guided Cathedal tour",    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    newPrice: "65",
    location: "Barcelona",
    category: "attractions",
    cancellation:'none',
    duration:'2'
  },

  {
    img: "https://hldak.mmtcdn.com/prod-s3-hld-hpcmsadmin/holidays/images/cities/235/vienna1.jpg?crop=259:168&downsize=259:168",
    title: "Westmister Walking tour & Westmister with ",
    title1:" Abbey entry London",
    title2:"guided Cathedal tour",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    newPrice: "65",
    location: "New York",
    category: "day trips",
    cancellation:'free cancellation',
    duration:'2'
  },

  {
    img: "https://hldak.mmtcdn.com/prod-s3-hld-hpcmsadmin/holidays/images/cities/235/vienna1.jpg?crop=259:168&downsize=259:168",
    title: "Westmister Walking tour & Westmister with ",
    title1:" Abbey entry London",
    title2:"guided Cathedal tour",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    newPrice: "65",
    location: "New York",
    category: "day trips",
    cancellation:'free cancellation',
    duration:'2'
  },
  {
    img: "https://hldak.mmtcdn.com/prod-s3-hld-hpcmsadmin/holidays/images/cities/235/vienna1.jpg?crop=259:168&downsize=259:168",
    title: "Westmister Walking tour & Westmister with ",
    title1:" Abbey entry London",
    title2:"guided Cathedal tour",    
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    newPrice: "65",
    location: "New York",
    category: "day trips",
    cancellation:'free cancellation',
    duration:'2'
  },
  {
    img: "https://hldak.mmtcdn.com/prod-s3-hld-hpcmsadmin/holidays/images/cities/235/vienna1.jpg?crop=259:168&downsize=259:168",
    title: "Westmister Walking tour & Westmister with ",
    title1:" Abbey entry London",
    title2:"guided Cathedal tour",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    newPrice: "500",
    location: "New York",
    category: "day trips",
    cancellation:'none',
    duration:'10'
  },
  {
    img: "https://hldak.mmtcdn.com/prod-s3-hld-hpcmsadmin/holidays/images/cities/235/vienna1.jpg?crop=259:168&downsize=259:168",
    title: "Westmister Walking tour & Westmister with ",
    title1:" Abbey entry London",
    title2:"guided Cathedal tour",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    newPrice: "250",
    location: "Rome",
    category: "outdoor activities",
    cancellation:'free cancellation',
    duration:'20'
  },
  {
    img: "https://hldak.mmtcdn.com/prod-s3-hld-hpcmsadmin/holidays/images/cities/235/vienna1.jpg?crop=259:168&downsize=259:168",
    title: "Westmister Walking tour & Westmister with ",
    title1:" Abbey entry London",
    title2:"guided Cathedal tour",
        star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    newPrice: "350",
    location: "Rome",
    category: "outdoor activities",
    cancellation:'free cancellation',
    duration:'20'
  },

  {
    img: "https://hldak.mmtcdn.com/prod-s3-hld-hpcmsadmin/holidays/images/cities/235/vienna1.jpg?crop=259:168&downsize=259:168",
    title: "High Speed Thames River RIB cruise in Rome Rome with Guided Cathedal tour",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    newPrice: "450",
    location: "Rome",
    category: "outdoor activities",
    cancellation:'free cancellation',
    duration:'20'
  },
  {
    img: "https://hldak.mmtcdn.com/prod-s3-hld-hpcmsadmin/holidays/images/cities/235/vienna1.jpg?crop=259:168&downsize=259:168",
    title: "Westmister Walking tour & Westmister with ",
    title1:" Abbey entry London",
    title2:"guided Cathedal tour",
        star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    newPrice: "250",
    location: "Rome",
    category: "outdoor activities",
    cancellation:'none',
    duration:'14'
  },
  {
    img: "https://hldak.mmtcdn.com/prod-s3-hld-hpcmsadmin/holidays/images/cities/235/vienna1.jpg?crop=259:168&downsize=259:168",
    title: "Westmister Walking tour & Westmister with ",
    title1:" Abbey entry London",
    title2:"guided Cathedal tour",
        star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    newPrice: "250",
    location: "Paris",
    cancellation:'free cancellation',
    category: "concert and shows",
    duration:'14'
  },
  {
    img: "https://hldak.mmtcdn.com/prod-s3-hld-hpcmsadmin/holidays/images/cities/235/vienna1.jpg?crop=259:168&downsize=259:168",
    title: "Westmister Walking tour & Westmister with ",
    title1:" Abbey entry London",
    title2:"guided Cathedal tour",
        star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    newPrice: "250",
    location: "Paris",
    cancellation:'free cancellation',
    category: "concert and shows",
    duration:'14'
  },
  {
    img: "https://hldak.mmtcdn.com/prod-s3-hld-hpcmsadmin/holidays/images/cities/235/vienna1.jpg?crop=259:168&downsize=259:168",
    title: "Westmister Walking tour & Westmister with ",
    title1:" Abbey entry London",
    title2:"guided Cathedal tour",
        star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    newPrice: "250",
    location: "Paris",
    cancellation:'free cancellation',
    category: "concert and shows",
    duration:'13'
  },
  {
    img: "https://hldak.mmtcdn.com/prod-s3-hld-hpcmsadmin/holidays/images/cities/235/vienna1.jpg?crop=259:168&downsize=259:168",
    title: "Westmister Walking tour & Westmister with ",
    title1:" Abbey entry London",
    title2:"guided Cathedal tour",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    newPrice: "250",
    location: "Paris",
    cancellation:'free cancellation',
    category: "concert and shows",
    duration:'12'
  },
  {
    img: "https://hldak.mmtcdn.com/prod-s3-hld-hpcmsadmin/holidays/images/cities/235/vienna1.jpg?crop=259:168&downsize=259:168",
    title: "Westmister Walking tour & Westmister with ",
    title1:" Abbey entry London",
    title2:"guided Cathedal tour",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    newPrice: "250",
    location: "Paris",
    cancellation:'free cancellation',
    category: "concert and shows",
    duration:'14'
  },
  {
    img: "https://hldak.mmtcdn.com/prod-s3-hld-hpcmsadmin/holidays/images/cities/235/vienna1.jpg?crop=259:168&downsize=259:168",
    title: "Westmister Walking tour & Westmister with ",
    title1:" Abbey entry London",
    title2:"guided Cathedal tour",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    newPrice: "150",
    location: "Berlin",
    cancellation:'free cancellation',
    category: "concert and shows",
    duration:'19'
  },
  {
    img: "https://hldak.mmtcdn.com/prod-s3-hld-hpcmsadmin/holidays/images/cities/235/vienna1.jpg?crop=259:168&downsize=259:168",
    title: "Westmister Walking tour & Westmister with ",
    title1:" Abbey entry London",
    title2:"guided Cathedal tour",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    newPrice: "150",
    location: "Berlin",
    cancellation:'free cancellation',
    category: "concert and shows",
    duration:'free cancellation'
  },

  {
    img: "https://hldak.mmtcdn.com/prod-s3-hld-hpcmsadmin/holidays/images/cities/235/vienna1.jpg?crop=259:168&downsize=259:168",
    title: "Westmister Walking tour & Westmister with ",
    title1:" Abbey entry London",
    title2:"guided Cathedal tour",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    newPrice: "150",
    location: "Berlin",
    cancellation:'free cancellation',
    category: "concert and shows",
    duration:'2'
  },
  {
    img: "https://hldak.mmtcdn.com/prod-s3-hld-hpcmsadmin/holidays/images/cities/235/vienna1.jpg?crop=259:168&downsize=259:168",
    title: "Westmister Walking tour & Westmister with ",
    title1:" Abbey entry London",
    title2:"guided Cathedal tour",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    newPrice: "50",
    location: "Berlin",
    cancellation:'free cancellation',
    category: "concert and shows",
    duration:'14'
  },
  {
    img: "https://hldak.mmtcdn.com/prod-s3-hld-hpcmsadmin/holidays/images/cities/235/vienna1.jpg?crop=259:168&downsize=259:168",
    title: "Westmister Walking tour & Westmister with ",
    title1:" Abbey entry London",
    title2:"guided Cathedal tour",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    newPrice: "50",
    location: "Berlin",
    cancellation:'free cancellation',
    category: "concert and shows",
    duration:'20'
  },
  {
    img: "https://m.media-amazon.com/images/I/61uw5RDxKQL._AC_UY625_.jpg",
    title: "dinburgh Darkside Walking tours Mourders and legends Berlin with tours",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    newPrice: "50",
    location: "Berlin",
    cancellation:'free cancellation',
    category: "Tours",
    duration:'3'
  },
  {
    img: "https://hldak.mmtcdn.com/prod-s3-hld-hpcmsadmin/holidays/images/cities/235/vienna1.jpg?crop=259:168&downsize=259:168",
    title: "Westmister Walking tour & Westmister with ",
    title1:" Abbey entry London",
    title2:"guided Cathedal tour",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    newPrice: "50",
    location: "Berlin",
    cancellation:'none',
    category: "Attraction and Museum",
    duration:'1'
  },
];

export default data;
